version: '3.8'
services:
  git-server:
    build: ./git
    container_name: git
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ../data/repos:/var/www/git

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ../data/sonarqube_conf:/opt/sonarqube/conf
      - ../data/sonarqube_data:/opt/sonarqube/data
 
  jenkins:
    build: ./jenkins
    container_name: jenkins
    restart: always
    user: root
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - ../data/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
 
  webapp:
    build: ./webapp
    container_name: webapp
    restart: always
    ports:
      - "5000"
